# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddSettingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddSettingWindow(object):
    def setupUi(self, AddSettingWindow):
        AddSettingWindow.setObjectName("AddSettingWindow")
        AddSettingWindow.resize(426, 199)
        self.horizontalLayoutWidget = QtWidgets.QWidget(AddSettingWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 150, 228, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonConfirm = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.horizontalLayout.addWidget(self.pushButtonConfirm)
        self.pushButtonCancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(AddSettingWindow)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(90, 40, 251, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_2.addWidget(self.label_1)
        self.lineEditName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditName.setObjectName("lineEditName")
        self.horizontalLayout_2.addWidget(self.lineEditName)

        self.retranslateUi(AddSettingWindow)
        QtCore.QMetaObject.connectSlotsByName(AddSettingWindow)

    def retranslateUi(self, AddSettingWindow):
        _translate = QtCore.QCoreApplication.translate
        AddSettingWindow.setWindowTitle(_translate("AddSettingWindow", "添加新参数名称界面"))
        self.pushButtonConfirm.setText(_translate("AddSettingWindow", "确定"))
        self.pushButtonCancel.setText(_translate("AddSettingWindow", "取消"))
        self.label_1.setText(_translate("AddSettingWindow", "新参数类型名称："))
