# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddUserWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddUserWindow(object):
    def setupUi(self, AddUserWindow):
        AddUserWindow.setObjectName("AddUserWindow")
        AddUserWindow.resize(426, 199)
        self.verticalLayoutWidget = QtWidgets.QWidget(AddUserWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 30, 83, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(AddUserWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 130, 228, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.confirmButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(AddUserWindow)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 30, 151, 81))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditUsername = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.verticalLayout_2.addWidget(self.lineEditUsername)
        self.lineEditPassword = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout_2.addWidget(self.lineEditPassword)
        self.lineEditConfirmPassword = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditConfirmPassword.setObjectName("lineEditConfirmPassword")
        self.verticalLayout_2.addWidget(self.lineEditConfirmPassword)

        self.retranslateUi(AddUserWindow)
        QtCore.QMetaObject.connectSlotsByName(AddUserWindow)

    def retranslateUi(self, AddUserWindow):
        _translate = QtCore.QCoreApplication.translate
        AddUserWindow.setWindowTitle(_translate("AddUserWindow", "添加用户界面"))
        self.label_1.setText(_translate("AddUserWindow", "用户名："))
        self.label_2.setText(_translate("AddUserWindow", "密码："))
        self.label_3.setText(_translate("AddUserWindow", "确认密码："))
        self.confirmButton.setText(_translate("AddUserWindow", "确定"))
        self.cancelButton.setText(_translate("AddUserWindow", "取消"))
