# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(426, 199)
        self.verticalLayoutWidget = QtWidgets.QWidget(LoginWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 30, 71, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(LoginWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 130, 228, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loginButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout.addWidget(self.loginButton)
        self.quitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.quitButton.setObjectName("quitButton")
        self.horizontalLayout.addWidget(self.quitButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(LoginWindow)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 30, 151, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditUsername = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.verticalLayout_2.addWidget(self.lineEditUsername)
        self.lineEditPassword = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout_2.addWidget(self.lineEditPassword)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "登录界面"))
        self.label_1.setText(_translate("LoginWindow", "用户名："))
        self.label_2.setText(_translate("LoginWindow", "密码："))
        self.loginButton.setText(_translate("LoginWindow", "登录"))
        self.quitButton.setText(_translate("LoginWindow", "退出"))
