# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingSubWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingSubWindow(object):
    def setupUi(self, SettingSubWindow):
        SettingSubWindow.setObjectName("SettingSubWindow")
        SettingSubWindow.resize(801, 571)
        self.groupBox_4 = QtWidgets.QGroupBox(SettingSubWindow)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 90, 171, 361))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label = QtWidgets.QLabel(self.groupBox_4)
        self.label.setGeometry(QtCore.QRect(10, 30, 71, 31))
        self.label.setObjectName("label")
        self.spinBoxPara1 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBoxPara1.setEnabled(True)
        self.spinBoxPara1.setGeometry(QtCore.QRect(70, 30, 91, 31))
        self.spinBoxPara1.setObjectName("spinBoxPara1")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 71, 31))
        self.label_2.setObjectName("label_2")
        self.doubleSpinBoxPara2 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBoxPara2.setGeometry(QtCore.QRect(70, 70, 91, 31))
        self.doubleSpinBoxPara2.setObjectName("doubleSpinBoxPara2")
        self.radioButtonPara3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonPara3.setGeometry(QtCore.QRect(100, 110, 21, 31))
        self.radioButtonPara3.setText("")
        self.radioButtonPara3.setObjectName("radioButtonPara3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 71, 31))
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(SettingSubWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 459, 171, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.groupBox_5 = QtWidgets.QGroupBox(SettingSubWindow)
        self.groupBox_5.setGeometry(QtCore.QRect(200, 10, 581, 551))
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox = QtWidgets.QGroupBox(SettingSubWindow)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 171, 71))
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(23, 30, 131, 26))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi(SettingSubWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingSubWindow)

    def retranslateUi(self, SettingSubWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingSubWindow.setWindowTitle(_translate("SettingSubWindow", "Form"))
        self.groupBox_4.setTitle(_translate("SettingSubWindow", "参数设置"))
        self.label.setText(_translate("SettingSubWindow", "参数1："))
        self.label_2.setText(_translate("SettingSubWindow", "参数2："))
        self.label_3.setText(_translate("SettingSubWindow", "参数3："))
        self.pushButton.setText(_translate("SettingSubWindow", "参数选择"))
        self.pushButton_3.setText(_translate("SettingSubWindow", "保存"))
        self.pushButton_2.setText(_translate("SettingSubWindow", "取消"))
        self.groupBox_5.setTitle(_translate("SettingSubWindow", "当前效果"))
        self.groupBox.setTitle(_translate("SettingSubWindow", "参数类型选择"))
