# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdateSettingNameWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateSettingNameWindow(object):
    def setupUi(self, UpdateSettingNameWindow):
        UpdateSettingNameWindow.setObjectName("UpdateSettingNameWindow")
        UpdateSettingNameWindow.resize(426, 199)
        self.horizontalLayoutWidget = QtWidgets.QWidget(UpdateSettingNameWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 150, 228, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonConfirm = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonConfirm.setObjectName("pushButtonConfirm")
        self.horizontalLayout.addWidget(self.pushButtonConfirm)
        self.pushButtonCancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(UpdateSettingNameWindow)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(90, 70, 251, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_1 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_2.addWidget(self.label_1)
        self.lineEditUpdatedName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditUpdatedName.setObjectName("lineEditUpdatedName")
        self.horizontalLayout_2.addWidget(self.lineEditUpdatedName)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(UpdateSettingNameWindow)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(90, 20, 251, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.labelCurrentName = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.labelCurrentName.setObjectName("labelCurrentName")
        self.horizontalLayout_3.addWidget(self.labelCurrentName)

        self.retranslateUi(UpdateSettingNameWindow)
        QtCore.QMetaObject.connectSlotsByName(UpdateSettingNameWindow)

    def retranslateUi(self, UpdateSettingNameWindow):
        _translate = QtCore.QCoreApplication.translate
        UpdateSettingNameWindow.setWindowTitle(_translate("UpdateSettingNameWindow", "修改参数名称界面"))
        self.pushButtonConfirm.setText(_translate("UpdateSettingNameWindow", "确定"))
        self.pushButtonCancel.setText(_translate("UpdateSettingNameWindow", "取消"))
        self.label_1.setText(_translate("UpdateSettingNameWindow", "新参数类型名称："))
        self.label_2.setText(_translate("UpdateSettingNameWindow", "当前参数类型名称："))
        self.labelCurrentName.setText(_translate("UpdateSettingNameWindow", "TextLabel"))
