# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UpdatePasswordWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdatePasswordWindow(object):
    def setupUi(self, UpdatePasswordWindow):
        UpdatePasswordWindow.setObjectName("UpdatePasswordWindow")
        UpdatePasswordWindow.resize(426, 199)
        self.verticalLayoutWidget = QtWidgets.QWidget(UpdatePasswordWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 10, 83, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(UpdatePasswordWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(100, 150, 228, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.confirmButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(UpdatePasswordWindow)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(180, 10, 151, 111))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_username = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_username.setObjectName("label_username")
        self.verticalLayout_2.addWidget(self.label_username)
        self.lineEditOldPassword = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditOldPassword.setObjectName("lineEditOldPassword")
        self.verticalLayout_2.addWidget(self.lineEditOldPassword)
        self.lineEditNewPassword = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditNewPassword.setObjectName("lineEditNewPassword")
        self.verticalLayout_2.addWidget(self.lineEditNewPassword)
        self.lineEditConfirmNewPassword = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditConfirmNewPassword.setObjectName("lineEditConfirmNewPassword")
        self.verticalLayout_2.addWidget(self.lineEditConfirmNewPassword)

        self.retranslateUi(UpdatePasswordWindow)
        QtCore.QMetaObject.connectSlotsByName(UpdatePasswordWindow)

    def retranslateUi(self, UpdatePasswordWindow):
        _translate = QtCore.QCoreApplication.translate
        UpdatePasswordWindow.setWindowTitle(_translate("UpdatePasswordWindow", "修改密码界面"))
        self.label_4.setText(_translate("UpdatePasswordWindow", "用户名："))
        self.label_1.setText(_translate("UpdatePasswordWindow", "原密码："))
        self.label_2.setText(_translate("UpdatePasswordWindow", "新密码："))
        self.label_3.setText(_translate("UpdatePasswordWindow", "确认新密码："))
        self.confirmButton.setText(_translate("UpdatePasswordWindow", "确定"))
        self.cancelButton.setText(_translate("UpdatePasswordWindow", "取消"))
        self.label_username.setText(_translate("UpdatePasswordWindow", "用户名"))
